using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AdmissionPortal_API.Domain.ExternalAPI
{
   public class PSEBModel
    {
        
        public class Response
        {
            public string FIRM { get; set; }
            public string RP { get; set; }
            public string CAT { get; set; }
            public string SET { get; set; }
            public string DIST { get; set; }
            public string SCHL { get; set; }
            public string CENT { get; set; }
            public string ROLL { get; set; }
            public string REGNO { get; set; }
            public string NAME { get; set; }
            public string PNAME { get; set; }
            public string FNAME { get; set; }
            public string PFNAME { get; set; }
            public string MNAME { get; set; }
            public string PMNAME { get; set; }
            public object ADOPFNAME { get; set; }
            public object ADOPPFNAME { get; set; }
            public object ADOPMNAME { get; set; }
            public object ADOPPMNAME { get; set; }
            public string DOB { get; set; }
            public string DOBW { get; set; }
            public string PHY_CHAL { get; set; }
            public string AREA { get; set; }
            public string RELIGION { get; set; }
            public string SEX { get; set; }
            public object MEDIUM { get; set; }
            public string SCHOOLE { get; set; }
            public string SCHOOLP { get; set; }
            public string WITHHELD { get; set; }
            public string SUB1 { get; set; }
            public string SPL1 { get; set; }
            public string SUBNAME1 { get; set; }
            public object OTH1 { get; set; }
            public string TH1 { get; set; }
            public string THMAX1 { get; set; }
            public string THMIN1 { get; set; }
            public string INA1 { get; set; }
            public string INAMAX1 { get; set; }
            public string INAMIN1 { get; set; }
            public string PR1 { get; set; }
            public string PRMAX1 { get; set; }
            public string PRMIN1 { get; set; }
            public string TOT1 { get; set; }
            public string MIN1 { get; set; }
            public string MAX1 { get; set; }
            public string RES1 { get; set; }
            public string GRADE1 { get; set; }
            public string SUB2 { get; set; }
            public string SPL2 { get; set; }
            public string SUBNAME2 { get; set; }
            public object OTH2 { get; set; }
            public string TH2 { get; set; }
            public string THMAX2 { get; set; }
            public string THMIN2 { get; set; }
            public string INA2 { get; set; }
            public string INAMAX2 { get; set; }
            public string INAMIN2 { get; set; }
            public string PR2 { get; set; }
            public string PRMAX2 { get; set; }
            public string PRMIN2 { get; set; }
            public string TOT2 { get; set; }
            public string MIN2 { get; set; }
            public string MAX2 { get; set; }
            public string RES2 { get; set; }
            public string GRADE2 { get; set; }
            public string SUB3 { get; set; }
            public string SPL3 { get; set; }
            public string SUBNAME3 { get; set; }
            public object OTH3 { get; set; }
            public string TH3 { get; set; }
            public string THMAX3 { get; set; }
            public string THMIN3 { get; set; }
            public string INA3 { get; set; }
            public string INAMAX3 { get; set; }
            public string INAMIN3 { get; set; }
            public string PR3 { get; set; }
            public string PRMAX3 { get; set; }
            public string PRMIN3 { get; set; }
            public string TOT3 { get; set; }
            public string MIN3 { get; set; }
            public string MAX3 { get; set; }
            public string RES3 { get; set; }
            public string GRADE3 { get; set; }
            public string SUB4 { get; set; }
            public string SPL4 { get; set; }
            public string SUBNAME4 { get; set; }
            public object OTH4 { get; set; }
            public string TH4 { get; set; }
            public string THMAX4 { get; set; }
            public string THMIN4 { get; set; }
            public string INA4 { get; set; }
            public string INAMAX4 { get; set; }
            public string INAMIN4 { get; set; }
            public string PR4 { get; set; }
            public string PRMAX4 { get; set; }
            public string PRMIN4 { get; set; }
            public string TOT4 { get; set; }
            public string MIN4 { get; set; }
            public string MAX4 { get; set; }
            public string RES4 { get; set; }
            public string GRADE4 { get; set; }
            public string SUB5 { get; set; }
            public string SPL5 { get; set; }
            public string SUBNAME5 { get; set; }
            public object OTH5 { get; set; }
            public string TH5 { get; set; }
            public string THMAX5 { get; set; }
            public string THMIN5 { get; set; }
            public string INA5 { get; set; }
            public string INAMAX5 { get; set; }
            public string INAMIN5 { get; set; }
            public string PR5 { get; set; }
            public string PRMAX5 { get; set; }
            public string PRMIN5 { get; set; }
            public string TOT5 { get; set; }
            public string MIN5 { get; set; }
            public string MAX5 { get; set; }
            public string RES5 { get; set; }
            public string GRADE5 { get; set; }
            public string SUB6 { get; set; }
            public string SPL6 { get; set; }
            public string SUBNAME6 { get; set; }
            public object OTH6 { get; set; }
            public string TH6 { get; set; }
            public string THMAX6 { get; set; }
            public string THMIN6 { get; set; }
            public string INA6 { get; set; }
            public string INAMAX6 { get; set; }
            public string INAMIN6 { get; set; }
            public string PR6 { get; set; }
            public string PRMAX6 { get; set; }
            public string PRMIN6 { get; set; }
            public string TOT6 { get; set; }
            public string MIN6 { get; set; }
            public string MAX6 { get; set; }
            public string RES6 { get; set; }
            public string GRADE6 { get; set; }
            public string SUB7 { get; set; }
            public string SPL7 { get; set; }
            public string SUBNAME7 { get; set; }
            public object OTH7 { get; set; }
            public string TH7 { get; set; }
            public string THMAX7 { get; set; }
            public string THMIN7 { get; set; }
            public string INA7 { get; set; }
            public string INAMAX7 { get; set; }
            public string INAMIN7 { get; set; }
            public string PR7 { get; set; }
            public string PRMAX7 { get; set; }
            public string PRMIN7 { get; set; }
            public string TOT7 { get; set; }
            public string MIN7 { get; set; }
            public string MAX7 { get; set; }
            public string RES7 { get; set; }
            public string GRADE7 { get; set; }
            public string SUB8 { get; set; }
            public string SPL8 { get; set; }
            public string SUBNAME8 { get; set; }
            public object OTH8 { get; set; }
            public string TH8 { get; set; }
            public string THMAX8 { get; set; }
            public string THMIN8 { get; set; }
            public string INA8 { get; set; }
            public string INAMAX8 { get; set; }
            public string INAMIN8 { get; set; }
            public string PR8 { get; set; }
            public string PRMAX8 { get; set; }
            public string PRMIN8 { get; set; }
            public string TOT8 { get; set; }
            public string MIN8 { get; set; }
            public string MAX8 { get; set; }
            public string RES8 { get; set; }
            public string GRADE8 { get; set; }
            public string SUB9 { get; set; }
            public string SPL9 { get; set; }
            public string SUBNAME9 { get; set; }
            public object OTH9 { get; set; }
            public string TH9 { get; set; }
            public string THMAX9 { get; set; }
            public string THMIN9 { get; set; }
            public string INA9 { get; set; }
            public string INAMAX9 { get; set; }
            public string INAMIN9 { get; set; }
            public string PR9 { get; set; }
            public string PRMAX9 { get; set; }
            public string PRMIN9 { get; set; }
            public string TOT9 { get; set; }
            public string MIN9 { get; set; }
            public string MAX9 { get; set; }
            public string RES9 { get; set; }
            public string GRADE9 { get; set; }
            public string SUB10 { get; set; }
            public string SPL10 { get; set; }
            public string SUBNAME10 { get; set; }
            public object OTH10 { get; set; }
            public string TH10 { get; set; }
            public string THMAX10 { get; set; }
            public string THMIN10 { get; set; }
            public string INA10 { get; set; }
            public string INAMAX10 { get; set; }
            public string INAMIN10 { get; set; }
            public string PR10 { get; set; }
            public string PRMAX10 { get; set; }
            public string PRMIN10 { get; set; }
            public string TOT10 { get; set; }
            public string MIN10 { get; set; }
            public string MAX10 { get; set; }
            public string RES10 { get; set; }
            public string GRADE10 { get; set; }
            public string TOTAL { get; set; }
            public string TOTMAX { get; set; }
            public string RESULT { get; set; }
            public string GRADE { get; set; }
            public string RESULTDTL { get; set; }
            public string RSUB1 { get; set; }
            public string RSUB2 { get; set; }
            public string RSUB3 { get; set; }
            public string RSUB4 { get; set; }
            public string RSUB5 { get; set; }
            public string YEAR { get; set; }
            public string PSESSION { get; set; }
            public string ESESSION { get; set; }
            public object EXAMSRNO { get; set; }
            public object DUPCERTNO { get; set; }
            public object DOP { get; set; }
            public string PATH { get; set; }
            public object CORRECTION { get; set; }
            public string CDRNO { get; set; }
            public object CDATE { get; set; }
            public string SESSION { get; set; }
            public string CERT { get; set; }
            public string STATUS { get; set; }
            public string UPD { get; set; }
            public string ASSISTANT { get; set; }
            public string SUPERINTENDENT { get; set; }
            public string CLS { get; set; }
            public string YR { get; set; }
            public string GROUP { get; set; }
            public object ADOPPFNAME1 { get; set; }
            public object ADOPFNAME1 { get; set; }
            public object ADOPPMNAME1 { get; set; }
            public object ADOPMNAME1 { get; set; }
            public object CERTM { get; set; }
            public string UTYPE { get; set; }
            public string TEMPLATE { get; set; }
        }

        public class PSEBResult
        {
            public int status { get; set; }
            public List<Response> response { get; set; }
        }


    }

}
