---
apiVersion: v1
kind: Service
metadata:
  name: admission-ui
  namespace: admission
spec:
  type: NodePort
  selector:
    app:  admission-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  admission-ui
  namespace:  admission
spec:
  selector:
    matchLabels:
      app:  admission-ui
  replicas: 2
  template:
    metadata:
      labels:
        app:  admission-ui
    spec:
      containers:
      - name:  admission-ui
        image:  art.psegs.in/admission/ui:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 0.5Gi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "staging"
        - name: TZ
          value: "Asia/Kolkata"
      imagePullSecrets:
        - name: admission
  strategy:
    type: RollingUpdate
    rollingUpdate:
         maxUnavailable: 25%
         maxSurge: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: admission-ui
  namespace: admission
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admission-ui
  targetCPUUtilizationPercentage: 80
